name: Test:Md5UtilTest.assetGetTpContentMd5
run-name: Known Flaky test assetGetTpContentMd5
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: mvn -pl hippo4j-common test -Dtest=cn.hippo4j.common.toolkit.Md5UtilTest#assetGetTpContentMd5
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: mvn -pl hippo4j-common edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cn.hippo4j.common.toolkit.Md5UtilTest#assetGetTpContentMd5
